# Generated by Django 3.0.6 on 2020-07-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200617_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='template',
            name='description',
        ),
        migrations.RemoveField(
            model_name='template',
            name='skills',
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='TemplateAttribute',
        ),
        migrations.DeleteModel(
            name='TemplateSkill',
        ),
    ]
