# Generated by Django 3.0.6 on 2020-07-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200711_1720'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Template',
        ),
    ]
