# Generated by Django 3.0.6 on 2020-07-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0003_auto_20200714_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkillModel',
        ),
        migrations.DeleteModel(
            name='TemplateModel',
        ),
    ]
