# Generated by Django 3.0.6 on 2020-07-14 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0005_skillmodel_templatemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillmodel',
            name='related_template',
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='related_skills',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gamemaster.SkillModel'),
            preserve_default=False,
        ),
    ]
