# Generated by Django 3.0.6 on 2020-07-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0006_auto_20200714_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='related_skills',
        ),
        migrations.AddField(
            model_name='templatemodel',
            name='related_skills',
            field=models.ManyToManyField(to='gamemaster.SkillModel'),
        ),
    ]
