# Generated by Django 3.0.6 on 2020-07-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0007_auto_20200714_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemodel',
            old_name='related_skills',
            new_name='skills',
        ),
    ]
