# Generated by Django 3.0.6 on 2020-07-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0008_auto_20200714_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('min_value', models.IntegerField(default=0)),
                ('min_value_alt', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=100)),
                ('max_value_alt', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=100)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SkillModel',
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='skills',
            field=models.ManyToManyField(to='gamemaster.SkillTemplateModel'),
        ),
    ]
