# Generated by Django 3.0.6 on 2020-07-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamemaster', '0010_templatemodel_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatemodel',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='templatemodel',
            name='skills',
        ),
        migrations.DeleteModel(
            name='AttributeTemplateModel',
        ),
        migrations.DeleteModel(
            name='SkillTemplateModel',
        ),
        migrations.DeleteModel(
            name='TemplateModel',
        ),
    ]
