# Generated by Django 3.0.6 on 2020-07-15 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('min_value', models.IntegerField(default=0)),
                ('min_value_alt', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=100)),
                ('max_value_alt', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillTemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('min_value', models.IntegerField(default=0)),
                ('max_value', models.IntegerField(default=100)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('attributes', models.ManyToManyField(to='template.AttributeTemplateModel')),
                ('skills', models.ManyToManyField(to='template.SkillTemplateModel')),
            ],
        ),
    ]
