# Generated by Django 3.0.6 on 2020-07-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='attributes',
            field=models.ManyToManyField(null=True, to='template.AttributeTemplateModel'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='skills',
            field=models.ManyToManyField(null=True, to='template.SkillTemplateModel'),
        ),
    ]
