# Generated by Django 3.0.6 on 2020-07-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0002_auto_20200715_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='template.AttributeTemplateModel'),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='skills',
            field=models.ManyToManyField(blank=True, to='template.SkillTemplateModel'),
        ),
    ]
