# Generated by Django 3.0.8 on 2020-07-15 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alignment', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=255, unique=True)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=255, unique=True)),
                ('internal_size', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True)),
                ('armor_class', models.IntegerField(default=10)),
                ('armor_description', models.CharField(blank=True, max_length=255)),
                ('hit_points', models.IntegerField(default=4)),
                ('hit_points_alt', models.CharField(blank=True, max_length=255)),
                ('speed_base', models.IntegerField(blank=True, default=30)),
                ('speed_alt', models.CharField(blank=True, max_length=255)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('challenge', models.FloatField(default=1)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster.Alignment')),
                ('languages', models.ManyToManyField(to='monster.Language')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster.Race')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monster.Size')),
            ],
        ),
    ]
