# Generated by Django 3.0.8 on 2020-07-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race',
            field=models.CharField(max_length=255),
        ),
    ]
