# Generated by Django 3.0.8 on 2020-07-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0002_auto_20200715_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='challenge_xp',
            field=models.IntegerField(default=10),
        ),
    ]
