# Generated by Django 3.0.8 on 2020-07-15 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0003_monster_challenge_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monster',
            name='alignment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monster.Alignment'),
        ),
    ]
