# Generated by Django 3.0.8 on 2020-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0008_auto_20200715_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='actions',
            field=models.ManyToManyField(to='monster.Action'),
        ),
    ]
