# Generated by Django 3.0.8 on 2020-07-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0009_auto_20200715_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(default='', max_length=255)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='senses',
            field=models.ManyToManyField(to='monster.Sense'),
        ),
        migrations.AddField(
            model_name='monster',
            name='skills',
            field=models.ManyToManyField(to='monster.Skill'),
        ),
    ]
