# Generated by Django 3.0.8 on 2020-07-15 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0010_auto_20200715_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sense',
            name='value',
        ),
    ]
