# Generated by Django 3.0.8 on 2020-07-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0012_auto_20200715_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionImmunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_immunity', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DamageImmunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_immunity', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DamageResistance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_resistance', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='monster',
            name='condition_immunities',
            field=models.ManyToManyField(to='monster.ConditionImmunity'),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_immunities',
            field=models.ManyToManyField(to='monster.DamageImmunity'),
        ),
        migrations.AddField(
            model_name='monster',
            name='damage_resistances',
            field=models.ManyToManyField(to='monster.DamageResistance'),
        ),
    ]
